configName: sam_d20_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: ATSAMD20J18
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.4.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD20_DFP\3.0.20\samd20\atdf\ATSAMD20J18.atdf
