configName: sam_d20_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD20J18
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMD20_DFP\3.0.22\samd20\atdf\ATSAMD20J18.atdf
