files:
- generatedChecksum: E45D1648EFC10229D7BE94DB19221FF7
  logicalPath: config\sam_d20_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E45D1648EFC10229D7BE94DB19221FF7
- generatedChecksum: 9D80AC3586D3901C891166AC6A240557
  logicalPath: config\sam_d20_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9D80AC3586D3901C891166AC6A240557
- generatedChecksum: 951228DBE637C4CE699CF9549F6B2AF7
  logicalPath: config\sam_d20_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 951228DBE637C4CE699CF9549F6B2AF7
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_d20_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: ED286F19F7FF2D08578C1DA605D0EB8B
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED286F19F7FF2D08578C1DA605D0EB8B
- generatedChecksum: 17466C24256C98B3004320BEBA7CE80E
  logicalPath: config\sam_d20_xpro\peripheral\dac
  name: plib_dac.c
  physicalPath: peripheral\dac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 17466C24256C98B3004320BEBA7CE80E
- generatedChecksum: 1B72EBDAEF015670FE08DE23506A9BCA
  logicalPath: config\sam_d20_xpro\peripheral\eic
  name: plib_eic.c
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1B72EBDAEF015670FE08DE23506A9BCA
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: 62A9B5BB0612D33A0E992AAB65A7147A
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 62A9B5BB0612D33A0E992AAB65A7147A
- generatedChecksum: E85A8757F82A322C86C52D9BF238E9E1
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: E85A8757F82A322C86C52D9BF238E9E1
- generatedChecksum: A5EB52D19C376ACE2F2D153B953F1236
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: A5EB52D19C376ACE2F2D153B953F1236
- generatedChecksum: 2C7BD67143EE6596BA30C57B952742B2
  logicalPath: config\sam_d20_xpro\peripheral\tc
  name: plib_tc3.c
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2C7BD67143EE6596BA30C57B952742B2
- generatedChecksum: 2645E564BD945DAED1424FD8D7B39330
  logicalPath: config\sam_d20_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2645E564BD945DAED1424FD8D7B39330
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_d20_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
- generatedChecksum: DBC71687C01AED1E449ED8B829D68D75
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBC71687C01AED1E449ED8B829D68D75
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: EF7C3C5918A153FC7CB8C785309F1F42
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EF7C3C5918A153FC7CB8C785309F1F42
- generatedChecksum: 34813D598F208674B4B933EA0F16378F
  logicalPath: config\sam_d20_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 34813D598F208674B4B933EA0F16378F
- generatedChecksum: 66CFA0129C6BF7566769898343F9F5B5
  logicalPath: config\sam_d20_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 66CFA0129C6BF7566769898343F9F5B5
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d20_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: DF73F1FD406128CFF6DCDCF17B582138
  logicalPath: config\sam_d20_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: DF73F1FD406128CFF6DCDCF17B582138
- generatedChecksum: F7E9546F7C4EFD53476AA132B069BC26
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F7E9546F7C4EFD53476AA132B069BC26
- generatedChecksum: 23236B108D96C78FC087DE9F46329431
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 23236B108D96C78FC087DE9F46329431
- generatedChecksum: 27F1A8D568DC6E31B9FC9F133335B831
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 27F1A8D568DC6E31B9FC9F133335B831
- generatedChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
- generatedChecksum: 73936946C3E908B2F04AD2635B426D37
  logicalPath: config\sam_d20_xpro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 73936946C3E908B2F04AD2635B426D37
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
- generatedChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
- generatedChecksum: D9883C70E96468DEE4D7B4669D1C837B
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: D9883C70E96468DEE4D7B4669D1C837B
- generatedChecksum: 9290D4A79F86C3A3D1E5CE508A1A0DF4
  logicalPath: config\sam_d20_xpro\peripheral\dac
  name: plib_dac.h
  physicalPath: peripheral\dac
  security: NON_SECURE
  type: HEADER
  userChecksum: 9290D4A79F86C3A3D1E5CE508A1A0DF4
- generatedChecksum: B3807F159BDDE52E1B1539D4F80FF903
  logicalPath: config\sam_d20_xpro\peripheral\eic
  name: plib_eic.h
  physicalPath: peripheral\eic
  security: NON_SECURE
  type: HEADER
  userChecksum: B3807F159BDDE52E1B1539D4F80FF903
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 0409AF288BD2A745FC25E1D26F3AF678
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 0409AF288BD2A745FC25E1D26F3AF678
- generatedChecksum: 4C437A26246C74EDB636CA10B7B10568
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C437A26246C74EDB636CA10B7B10568
- generatedChecksum: 81BFD57D170620FCDEA9BC052F1F7967
  logicalPath: config\sam_d20_xpro\peripheral\tc
  name: plib_tc3.h
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: HEADER
  userChecksum: 81BFD57D170620FCDEA9BC052F1F7967
- generatedChecksum: 6DBEAF7BD42014F5492374805406687A
  logicalPath: config\sam_d20_xpro\peripheral\tc
  name: plib_tc_common.h
  physicalPath: peripheral\tc
  security: NON_SECURE
  type: HEADER
  userChecksum: 6DBEAF7BD42014F5492374805406687A
- generatedChecksum: 04C8E3C2A27856229F9387BED9467911
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 04C8E3C2A27856229F9387BED9467911
- generatedChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
- generatedChecksum: 8F5153CF14498A1492E057678BE86F0F
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F5153CF14498A1492E057678BE86F0F
- generatedChecksum: 7E3018CE00C07DD04076D474C2C8E201
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7E3018CE00C07DD04076D474C2C8E201
- generatedChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
  logicalPath: packs\ATSAMD20J18_DFP
  name: samd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
- generatedChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
  logicalPath: packs\ATSAMD20J18_DFP\pio
  name: samd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
- generatedChecksum: BF83964046BC16326781DC33DB004B7B
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BF83964046BC16326781DC33DB004B7B
- generatedChecksum: 8F8BAA01E847D7C106FDDF03F0735423
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F8BAA01E847D7C106FDDF03F0735423
- generatedChecksum: 69A268C7263485C322910EEFA8D97B5E
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 69A268C7263485C322910EEFA8D97B5E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d20_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: A102ED238794D81B3B354DBD9D8978FD
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A102ED238794D81B3B354DBD9D8978FD
- generatedChecksum: A24C9818BE52278D08A208C324917009
  logicalPath: config\sam_d20_xpro
  name: ATSAMD20J18.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A24C9818BE52278D08A208C324917009
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
